services:
  - type: web
    name: invoice-api
    runtime: python
    repo: https://github.com/NPKpadala/invoice-api
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
